[package]
name = "dmx-engine"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[dependencies]
prost = "0.14.1"
once_cell = "1.20"
rand = "0.9.2"
getrandom = { version = "0.3", features = ["wasm_js"] }

[build-dependencies]
prost-build = "0.14.1"
